/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Area: typeof import('./components/area/index.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    BreadCrumbs: typeof import('./components/layouts/BreadCrumbs.vue')['default']
    Editor: typeof import('./components/editor/index.vue')['default']
    Logo: typeof import('./components/layouts/logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectTree: typeof import('./components/selectTree/index.vue')['default']
    SelTree: typeof import('./components/selTree/index.vue')['default']
    TaskeSome: typeof import('./components/taske-some/index.vue')['default']
    UserItem: typeof import('./components/layouts/user-item.vue')['default']
  }
}
